version: "3.8"

services:
  frontend:
    image: rajaali890/frontend:latest
    ports:
      - "80:80"  # NGINX now serves on port 80 inside
    depends_on:
      - backend

  backend:
    image: rajaali890/backend:latest
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=yourpassword
      - DB_NAME=yourdbname
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: yourdbname
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
