version: "3.8"

services:
  frontend:
    build:
      context: ./Frontend
    ports:
      - "80:3000"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=yourpassword
      - DB_NAME=yourdbname
      - APP_PORT=5000
      - SESS_SECRET=yourSessionSecret
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: yourdbname
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
