name: Build and Deploy to EC2 from Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push frontend image
      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t rajaali890/frontend:latest ./Frontend
          docker push rajaali890/frontend:latest

      # Build and push backend image
      - name: Build and Push Backend Docker Image
        run: |
          docker build -t rajaali890/backend:latest ./Backend
          docker push rajaali890/backend:latest

      # Copy docker-compose.yml to EC2 (optional but keeps things clean)
      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "docker-compose.yml"
          target: "~/app"

      # SSH into EC2 and deploy
      - name: SSH and Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull rajaali890/frontend:latest
            docker pull rajaali890/backend:latest
            cd ~/app
            docker compose down
            docker compose up -d
